# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build NewsFuse Docs

on:
  push:
    branches: ["docs-cicd-testing"]
  pull_request:
    branches: ["docs-cicd-testing"]

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./newsfuse-func
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx sphinx-rtd-theme
      - name: Generate Docs
        run: |
          sphinx-apidoc -o ./docs/ ./newsfuse/
          sphinx-build -b html ./docs/ ./docs/_build
          ls -la ./docs/_build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
