# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build NewsFuse Function

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./newsfuse-func
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt
          python -m nltk.downloader punkt stopwords
      - name: Lint with flake8
        run: |
          flake8 ./newsfuse ./app.py --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ./newsfuse ./app.py --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics
      - name: Lint with mypy
        run: |
          mypy ./newsfuse ./app.py
      - name: Test with pytest
        run: |
          pytest .
